const debug = require('debug')('E:HelpMeCommand');
const BaseCommand = require('./baseCommand');
const logger = require('../logger');

class HelpMeCommand extends BaseCommand {
  execute() {
    super.execute();

    const response = 'Available Commands:\n\n'
      + '!helpme\n'
      + '!leavechannel\n'
      + '!resumeIntros\n'
      + '!stopIntros\n'
      + '!e\n'
      + '!anaconda2\n\n\n'
	  + 'Audios:\n\n'
      + '!yes\n'
      + '!yos\n'
      + '!shutup\n'
      + '!hola\n'
      + '!withme\n'
      + '!friend\n'
      + '!yugiboy\n'
      + '!fuckedup\n'
      + '!fixyou\n'
      + '!goat\n'
      + '!goat2\n'
      + '!kaiba\n'
	  + '!ah\n'
	  + '!bobby\n'
      + '!night\n'
	  + '!dedito\n'
      + '!pushme\n'
      + '!patineta\n'
	  + '!311\n'
	  + '!mrbubbs\n'
      + '!gijoe\n'
	  + '!hum\n'
	  + '!hum2\n'
	  + '!hum3\n'
	  + '!gustavo\n'
	  + '!vampire\n'
	  + '!hdp\n'
	  + '!skills\n'
	  + '!why\n'
	  + '!why2\n'
	  + '!preston\n'
	  + '!holdon\n'
	  + '!reflection\n'
	  + '!basta\n'
	  + '!basta2\n'
	  + '!spase\n'
	  + '!loquendo\n'
	  + '!chavo\n'
	  + '!chavo2\n'
	  + '!chavo3\n'
	  + '!jurio\n'
	  + '!amigo\n'
	  + '!celebrity\n'
      + '!bark\n'
	  + '!fly\n'
	  + '!buenisimo\n'
	  + '!punch\n'
	  + '!megadave\n'
	  + '!nagito\n'
	  + '!wrong\n'
	  + '!doping\n'
	  + '!fuckyouup\n'
	  + '!afilador\n'
	  + '!monokuma\n'
	  + '!barkcore\n'
	  + '!bondi\n'
	  + '!karaka\n'
	  + '!cubilla\n'
	  + '!cubille\n'
	  + '!karaka2\n'
	  + '!pinpin\n'
	  + '!sombrero\n'
	  + '!dinodoggo\n'
	  + '!cigarrillo\n'
	  + '!newtoy\n'
	  + '!quepasaaca\n'
	  + '!quepuasaaca\n'
      + '!thomas\n'
      + '!haha\n'
	  + '!samid\n'
	  + '!wallace\n'
	  + '!dinopain\n'
	  + '!thicc\n'
	  + '!superthicc\n'
	  + '!at\n'
	  + '!what\n'
	  + '!superwhat\n'
	  + '!atelier\n'
	  + '!works\n'
      + '!train';

    this.params.channel.send(response);
    debug(`Sent -> ${response}`);
    logger.info(`Sent -> ${response}`);
  }
}

module.exports = HelpMeCommand;
